class_name MusicLevels
## How loud each music file is, so that the game can play them all at one level.
## GENERATED by tools/music_levels.py: do not edit; after adding or swapping a track run
##     python3 tools/music_levels.py
## from the project root (an exported game cannot list the folder, hence a table).
## The trims (dB) bring a file to REFERENCE (LUFS, ITU-R BS.1770): TRIM as it is, for
## the world's music (Audio._update_music); SPEAKER_TRIM as it sounds through the car
## radio's dashboard speaker (170-5600 Hz, stereo pulled in to 0.4), for CarRadio. A file
## that is not in the table gets the median trim (DEFAULT_TRIM, DEFAULT_SPEAKER_TRIM).

const REFERENCE := -20.0
## Biquads in each of the speaker's filters as measured (AudioEffectFilter.db + 1).
const SPEAKER_STAGES := 1
const DEFAULT_TRIM := -6.0
const DEFAULT_SPEAKER_TRIM := -2.0
## File under res://art/audio/ -> dB. (Measured: loudness LUFS, plain RMS dBFS.)
const TRIM := {
	"music/carnival_band_organ.ogg":                 -3.2,  #  -16.8 LUFS,  -18.9 dB RMS
	"music/carnival_fun_and_games.mp3":              -7.1,  #  -12.9 LUFS,  -15.6 dB RMS
	"music/carnival_kidding_around.mp3":             -7.4,  #  -12.6 LUFS,  -14.5 dB RMS
	"music/day_bathed_in_the_light.ogg":             -6.0,  #  -14.0 LUFS,  -15.7 dB RMS
	"music/day_carpe_diem.ogg":                      -6.0,  #  -14.0 LUFS,  -15.9 dB RMS
	"music/day_heartwarming.ogg":                    -6.0,  #  -14.0 LUFS,  -17.0 dB RMS
	"music/day_laid_back_guitars.ogg":               -6.0,  #  -14.0 LUFS,  -16.2 dB RMS
	"music/day_relaxing_country.mp3":                -9.4,  #  -10.6 LUFS,  -13.1 dB RMS
	"music/day_relaxing_in_nature.mp3":             -14.4,  #   -5.6 LUFS,   -8.4 dB RMS
	"music/day_the_long_road.mp3":                   -5.7,  #  -14.3 LUFS,  -17.2 dB RMS
	"music/night_relaxation.mp3":                    -7.9,  #  -12.1 LUFS,  -14.9 dB RMS
	"music/radio/huzur_satie_gymnopedie_1.ogg":      -5.5,  #  -14.5 LUFS,  -17.5 dB RMS
	"music/radio/yesilova_uskudara_gider_iken.ogg":  -5.9,  #  -14.1 LUFS,  -17.9 dB RMS
	"music/radio/yesilova_yesilim.ogg":              -5.9,  #  -14.1 LUFS,  -16.8 dB RMS
	"music/radio/yol_bama_country.ogg":              -5.7,  #  -14.3 LUFS,  -14.9 dB RMS
	"music/radio/yol_cattails.ogg":                  -6.0,  #  -14.0 LUFS,  -16.3 dB RMS
}
## (Measured: loudness through the speaker, LUFS.)
const SPEAKER_TRIM := {
	"music/carnival_band_organ.ogg":                  0.7,  #  -20.7 LUFS
	"music/carnival_fun_and_games.mp3":              -5.0,  #  -15.0 LUFS
	"music/carnival_kidding_around.mp3":             -2.9,  #  -17.1 LUFS
	"music/day_bathed_in_the_light.ogg":             -1.0,  #  -19.0 LUFS
	"music/day_carpe_diem.ogg":                      -1.2,  #  -18.8 LUFS
	"music/day_heartwarming.ogg":                    -2.5,  #  -17.5 LUFS
	"music/day_laid_back_guitars.ogg":               -1.7,  #  -18.3 LUFS
	"music/day_relaxing_country.mp3":                -6.3,  #  -13.7 LUFS
	"music/day_relaxing_in_nature.mp3":             -10.1,  #   -9.9 LUFS
	"music/day_the_long_road.mp3":                   -2.0,  #  -18.0 LUFS
	"music/night_relaxation.mp3":                    -5.0,  #  -15.0 LUFS
	"music/radio/huzur_satie_gymnopedie_1.ogg":      -3.2,  #  -16.8 LUFS
	"music/radio/yesilova_uskudara_gider_iken.ogg":  -1.9,  #  -18.1 LUFS
	"music/radio/yesilova_yesilim.ogg":              -2.0,  #  -18.0 LUFS
	"music/radio/yol_bama_country.ogg":              -0.7,  #  -19.3 LUFS
	"music/radio/yol_cattails.ogg":                  -1.9,  #  -18.1 LUFS
}


## dB that brings `rel` (a file under res://art/audio/) to REFERENCE.
static func trim(rel: String) -> float:
	return float(TRIM.get(rel, DEFAULT_TRIM))


## The same as heard through the car radio's speaker.
static func speaker_trim(rel: String) -> float:
	return float(SPEAKER_TRIM.get(rel, DEFAULT_SPEAKER_TRIM))
